spring:
  profiles:
    active: prod
  application:
    name: Trello Scrum
    description: "API Trello Scrum"
    version: 0.0.1
    jwt:
      secret: TQczCdDxCAkbARkEYhXqDRSNe5qBV3S2jreQfKbQx86KKX66y52h8
      timeToExpire:
        token: 600
        refreshToken: 86400
  banner:
    charset: UTF-8
    location: banner.txt
  main:
    lazy-initialization: true
mybatis:
  mapper-locations: classpath*:**/mappers/*Mapper.xml
---
spring:
  profiles: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/trello_scrum?currentSchema=database
    username: root
    password: 123456
logging:
  level:
    com.dilsonjlrjr.javatrellodashboardmateus.mapper: trace
---
spring:
  profiles: prod
  datasource:
    url: jdbc:postgresql://nlwajauqrbphuu:dad475ba541fcee30185d2cf3de72d28341b847ba572701bb2631cf52376c8e5@ec2-34-225-103-117.compute-1.amazonaws.com:5432/daq0qvf5kc3fv3?currentSchema=database
    username: root
    password: 123456
